name: Ant build CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up junit
      run: |
        sudo sh -c "echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/force-unsafe-io"
        sudo apt-get -qq install junit > /dev/null
    - name: Download freenet.jar
      run: |
        sudo chown -R runner ../..
        mkdir -p ../fred/dist lib
        wget https://github.com/hyphanet/fred/releases/download/build01497/freenet.jar -qO ../fred/dist/freenet.jar
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Upload XMLSpider
      uses: actions/upload-artifact@v4
      with:
        name: plugin-XMLSpider
        path: dist/*
